/* eslint-disable max-len */
export default [
  {
    name: 'Texty Time',
    link: 'texty-time',
    platforms: ['Android'],
    desc: 'An app that helps you understand your textual relationships with others.' +
    ' It computes statistics about your texting habits with other people.',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Git'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.talkalytics&hl=en',
    previewImg: 'logo.png',
    headerImg: 'logo.png',
    imgFolder: 'texty-time',
    images: [
      'main.png',
      'all-time.png',
      'last-2-weeks.png',
      'emoticons.png',
      'compare.png',
      'favorites.png',
    ],
  },
  {
    name: 'Fridgly',
    link: 'fridgly',
    platforms: ['Android'],
    desc: 'An app that helps you keep track of your food expiration dates.' +
    ' It syncs with your Google Calendar to help remind you of when things are going to expire and when you should finish eating them.',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Pixelmator'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.foodcalendar',
    previewImg: 'logo.png',
    headerImg: 'logo.png',
    imgFolder: 'fridgly',
    images: [
      'main.png',
      'meat.png',
      'meat-veal.png',
      'fridge.png',
    ],
  },
  {
    name: 'Driller',
    link: 'driller',
    platforms: ['Android'],
    desc: 'An app that helps you keep track of your expenses.' +
    ' It provides detailed statistics about your spending habits to help you drill down into the areas in which you spend the most money.',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Pixelmator', 'Git'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.spending3',
    previewImg: 'logo.png',
    headerImg: 'logo.png',
    imgFolder: 'driller',
    images: [
      'transactions_google.png',
      'add_trans_google.png',
      'by_category_google.png',
      'by_category_food_google.png',
      'by_category_timeframe_google.png',
      'by_time_all_google.png',
      'by_time_food_google.png',
      'currency_google.png',
      'import_google.png',
    ],
  },
  {
    name: 'Olis',
    link: 'olis',
    platforms: ['Web', 'PC', 'OSX', 'Android', 'iOS'],
    desc: 'A business communication tool designed to help you keep the most important information visible.',
    tech: ['Javascript', 'React', 'Meteor', 'MongoDB', 'Electron', 'React Native', 'Digital Ocean', 'Sketch', 'Git'],
    url: 'https://www.olisapp.com/',
    previewImg: null,
    headerImg: null,
    images: [],
  },
  {
    name: 'Olis Landing Page',
    link: 'olis-landing',
    platforms: ['Web'],
    desc: 'A landing page for Olis.',
    tech: ['Javascript', 'React', 'Sketch'],
    url: 'http://www.getolis.com/',
    previewImg: null,
    headerImg: null,
    images: [],
  },
  {
    name: 'ReactForge',
    link: 'react-forge',
    platforms: ['Web'],
    desc: 'A landing page for ReactForge, a React-based web development agency.',
    tech: ['Javascript', 'React', 'Webpack', 'Sketch'],
    url: 'http://www.reactforge.com/',
    previewImg: null,
    headerImg: null,
    images: [],
  },
  {
    name: 'Decide-o-Tron',
    link: 'decide-o-tron',
    platforms: ['Web'],
    desc: 'A tool to help you make hard decisions.',
    tech: ['Javascript', 'React', 'Webpack', 'MobX', 'Sketch', 'Digital Ocean', 'Git'],
    url: 'http://decideotron.xyz',
    previewImg: null,
    headerImg: null,
    images: [],
  },
];
