/* eslint-disable max-len */
export default [
  {
    name: 'Texty Time',
    platform: 'Android',
    desc: '',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Git'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.talkalytics&hl=en',
    images: [],
  },
  {
    name: 'Fridgly',
    platform: 'Android',
    desc: '',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Pixelmator'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.foodcalendar',
    images: [],
  },
  {
    name: 'Driller',
    platform: 'Android',
    desc: '',
    tech: ['Java', 'Android Studio', 'Inkscape', 'Pixelmator', 'Git'],
    url: 'https://play.google.com/store/apps/details?id=com.aheadstudios.spending3',
    images: [],
  },
  {
    name: 'Olis',
    platform: ['Web', 'PC', 'OSX', 'Android', 'iOS'],
    desc: '',
    tech: ['Javascript', 'React', 'Meteor', 'MongoDB', 'Electron', 'React Native', 'Digital Ocean', 'Sketch', 'Git'],
    url: 'https://www.olisapp.com/',
    images: [],
  },
  {
    name: 'Olis Landing Page',
    platform: ['Web'],
    desc: 'A landing page for Olis.',
    tech: ['Javascript', 'React', 'Sketch'],
    url: 'http://www.getolis.com/',
    images: [],
  },
  {
    name: 'Decide-o-Tron',
    platform: ['Web'],
    desc: '',
    tech: ['Javascript', 'React', 'Webpack', 'MobX', 'Sketch', 'Digital Ocean', 'Git'],
    url: 'http://decideotron.xyz',
    images: [],
  },
];
